### ISSUE TITLE
Send to the backend a shortened link

### ISSUE THREAD

**Issue by alexsicart** [FileNation/FileNation#56]
Instead of sending the large ipfs link, send a bit.ly, link to the user.

**Comment by VictorBjelkholm** [comment]
Hm, this would kind of destroy the purpose of having the links being hashes. What if you don't have access to bit.ly or bit.ly shuts down? Then those URLs are gone basically.

Instead, you can use a different hashing algorithm or base encoding, to create a smaller hash.

**Comment by alexsicart** [comment]
Yes I completely agree with you. The use of these services like bit.ly, makes no sense and it centralize everything to them. 

Yes, it would be the best way. Or also creating a decentralized.cloud/{hash} or {filename} that be the link, but it has the problem is also centralized..., so no. @VictorBjelkholm there is a way in which decentralized.cloud/ipfs/ be a gateway?
