### ISSUE TITLE
Bugs on Firefox

### ISSUE THREAD

**Issue by alexsicart** [FileNation/FileNation#58]
When you are trying to upload a file, and checks it. The checking file label, doesn't disappear after the process.

**Comment by cboyce183** [comment]
I think this is related to file size somehow - an issue we encountered when using Firefox Quantum upon its release. It could also be a depreciated webkit or something like that. Looking into it.

**Comment by alexsicart** [comment]
@cboyce183 Yes It completely works on chrome, but not in firefox. maybe depreciated modules. :(
