### ISSUE TITLE
Add a message to go with each transfer.

### ISSUE THREAD

**Issue by alexsicart** [FileNation/FileNation#69]
When you add your files, and the recipient. Add the possibility to send a message to go with the transfer.

**Comment by marion59000** [comment]
Hi @alexsicart, I would like to work on this issue, is it possible?

**Comment by Olkliuchnyk** [comment]
Hi @alexsicart! Could you please add an optional param 'message' to the https://mighty-headland-68035.herokuapp.com/createEmail method?"

**Comment by alexsicart** [comment]
@Olkliuchnyk Sure!

**Comment by alexsicart** [comment]
@Olkliuchnyk Done!! :)
