### ISSUE TITLE
Redux with ngrx?

### ISSUE THREAD

**Issue by verygreenboi** [FileNation/FileNation#72]
What do you think about implementing Redux with NgRX? I know that it would add a lot of code but the payoff is worth it.

**Comment by alexsicart** [comment]
It would be amazing @verygreenboi Want to contribute? Starting with this redux implementation? :)

**Comment by verygreenboi** [comment]
I'll give it a shot.

**Comment by alexsicart** [comment]
Cool @verygreenboi
